### ISSUE TITLE
Array out of bound

### ISSUE THREAD

**Issue by lanquemar** [JamesAndAdrien/hello-world#2]
An array ALWAYS start at index 0.

You wrote:
https://github.com/JamesAndAdrien/hello-world/blob/964d6804ba755b94404ad88c060f8dd0ed3a9839/Game#L35-L39

**Comment by JamesAndAdrien** [comment]
oh that's a pretty good point

**Comment by lanquemar** [comment]
Fixed in 87c3df57f1100af6d83a23251c7b9b7d63dac78d
